# Generated by Django 4.1.3 on 2022-11-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_cart_user_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to='images/'),
        ),
    ]
