# Generated by Django 4.1.3 on 2022-11-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BT', 'Bottom Wear'), ('SP', 'Sport')], max_length=2),
        ),
    ]
