# Generated by Django 4.1.3 on 2022-11-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=1, max_length=100, null=True),
        ),
    ]
